Exit tests always with code 0

diff --git a/.github/workflows/voms-aa.ci.yml b/.github/workflows/voms-aa.ci.yml
--- a/.github/workflows/voms-aa.ci.yml
+++ b/.github/workflows/voms-aa.ci.yml
@@ -66,14 +66,15 @@ jobs:
 
       - name: Run testsuite for java clients
         run: |
-          docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh
+          docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh || true
           result=$(cat /tmp/reports/report.html | grep '^window.output\["stats"\]' | sed -e 's/window.output\["stats"\] = //' -e 's/;$//')
           java_passed_tests=$(echo "${result}" | jq .[0][0].pass)
           java_failed_tests=$(echo "${result}" | jq .[0][0].fail)
           echo "JAVA_PASSED_TESTS=${java_passed_tests}" >> "${GITHUB_ENV}"
           echo "JAVA_FAILED_TESTS=${java_failed_tests}" >> "${GITHUB_ENV}"
+          echo "Java passed tests: $JAVA_PASSED_TESTS"
+          echo "Java failed tests: $JAVA_FAILED_TESTS"
         working-directory: compose
-        continue-on-error: true
 
       - name: Collect test report for java clients
         if: ${{ always() }}
@@ -84,7 +85,7 @@ jobs:
         id: tests
         run: |
           docker compose --file docker-compose.ci.yml exec -T -u root testsuite bash -c "update-alternatives --set voms-proxy-init /usr/bin/voms-proxy-init2; update-alternatives --set voms-proxy-info /usr/bin/voms-proxy-info2; update-alternatives --set voms-proxy-destroy /usr/bin/voms-proxy-destroy2"
-          docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh --variable client_version:2 --include legacy
+          docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh --variable client_version:2 --include legacy || true
           result=$(cat /tmp/reports/report.html | grep '^window.output\["stats"\]' | sed -e 's/window.output\["stats"\] = //' -e 's/;$//')
           cpp_passed_tests=$(echo "${result}" | jq .[0][0].pass)
           cpp_failed_tests=$(echo "${result}" | jq .[0][0].fail)
@@ -128,7 +129,7 @@ jobs:
     needs: [run_testsuite_vomsaa]
     steps:
       - run: |
-          results='${{ toJSON(needs.run_testsuite_vomsaa.outputs) }}'
+          results='${{ needs.run_testsuite_vomsaa.outputs }}'
           echo $results | jq
           echo "# Test report" >> $GITHUB_STEP_SUMMARY
           echo "|                          | VOMS AA stable | VOMS AA beta |" >> $GITHUB_STEP_SUMMARY
