Hopefully clearer error report

diff --git a/.github/workflows/voms-aa.ci.yml b/.github/workflows/voms-aa.ci.yml
--- a/.github/workflows/voms-aa.ci.yml
+++ b/.github/workflows/voms-aa.ci.yml
@@ -53,7 +53,12 @@ jobs:
         working-directory: compose
 
       - name: Run testsuite for java clients
-        run: docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh
+        run: |
+          docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh
+          RESULT=$?
+          if [ $RESULT -ne 0 ]; then
+            echo "::error title=Java Tests Failed::${RESULT} Java tests failed"
+          fi
         working-directory: compose
         continue-on-error: true
 
@@ -68,6 +73,10 @@ jobs:
         run: |
           docker compose --file docker-compose.ci.yml exec -T -u root testsuite bash -c "update-alternatives --set voms-proxy-init /usr/bin/voms-proxy-init2; update-alternatives --set voms-proxy-info /usr/bin/voms-proxy-info2; update-alternatives --set voms-proxy-destroy /usr/bin/voms-proxy-destroy2"
           docker compose --file docker-compose.ci.yml exec -T -e ROBOT_OPTIONS="${ROBOT_OPTIONS}" testsuite bash /scripts/ci-run-testsuite.sh --variable client_version:2 --include legacy
+          RESULT=$?
+          if [ $RESULT -ne 0 ]; then
+            echo "::error title=C++ Tests Failed::${RESULT} C++ tests failed"
+          fi
         working-directory: compose
         continue-on-error: true
 
